name: Maumero New York
favicon: null
layout_spectrum: 0.9222102873027325
typography_spectrum: 0.18575284304097295
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.24038693006150424
  lightness: 0.9529379683081061
  saturation: 0.3333604116924107
  rhythmicContrast: 0.7207012593280524
purpose: []
